# Generated by Django 3.1.2 on 2022-03-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photnum',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
